### ISSUE TITLE
PreparedStatement Adding Multiple Tables

### ISSUE THREAD

**Issue by eredisg** [sgtcaze/ZombieEscape#26]
When I go to load a profile and create it, and log off and log back in, It creates a new table leading to duplicate entries.

**Comment by sgtcaze** [comment]
The newest code hasn't been pushed yet. This version has a few issues that were fixed before the most recent test.

**Comment by eredisg** [comment]
Do you have an ETA when it will be pushed?

**Comment by sgtcaze** [comment]
I hope it will be out before next Wednesday. I am currently cleaning up the code and adding some new features.

**Comment by eredisg** [comment]
Alright, Thanks
