### ISSUE TITLE
@Getter, OrderComparator and HoloAPI problem

### ISSUE THREAD

**Issue by Tim3game-zz** [sgtcaze/ZombieEscape#28]
Hello,

i wanted for a longer time to create my own minigame and i watched your tutorials for this minigame, but i ended whit 1 episode (after the 0 episode) and i have @Getter and OrderComparator error but i followed your tutorial, what is the problem ? PS: The HoloAPI 2.2 doesn't work for me, whats bad ?

http://prntscr.com/c7yetx
http://prntscr.com/c7yf4k
http://prntscr.com/c7yfgi

**Comment by tevin-cole** [comment]
If you're using IntelliJ you'll have to install the Lombok plugin instructions can be found [here](https://github.com/mplushnikov/lombok-intellij-plugin) and make sure you refresh Maven repositories to make sure that it got all its dependency.

**Comment by Tim3game-zz** [comment]
@frostythedev no, I using Eclipse, for IntelliJ i don't have the money.

**Comment by tevin-cole** [comment]
@Tim3game  There's a tutorial on the page for lombok for Eclipse also

**Comment by Tim3game-zz** [comment]
Probably I'm stupid but I don't found it, just how to install via the build-in plugin Installing, but Eclipse probably does not have it or I am blind but I did not find it, so I tried to download lambok from the site, so I installed it, but it don't work. I know I'm annoying and stupid, but i making whit maven the first time, so sorry. PS: Sorry for the english grammar

**Comment by sgtcaze** [comment]
IntelliJ is free to use.

I am going to update this project soon and rip out old dependencies. With the addition of the ArmorStand API, it seems redundant to have HolographicDisplays.

To use lombok in Eclipse, download this: https://projectlombok.org/download.html
Select your eclipse install folder then click install. After it finishes you just have to restart.

**Comment by Tim3game-zz** [comment]
ITS FREE? I haved a 30 day trial version, and on the page i found [this](https://www.jetbrains.com/idea/buy/#edition=personal.). If its really free, can you send me the page please? And i updated lambok, to 1.16.10 and its works, now i can continue whit your tutorials, thanks :)

**Comment by sgtcaze** [comment]
Yeah download the community edition version: https://www.jetbrains.com/idea/download/download-thanks.html?platform=windows&code=IIC

**Comment by Tim3game-zz** [comment]
I idiot, i downloaded the wrong version xD thanks :)
