### ISSUE TITLE
Plugin Wont Start

### ISSUE THREAD

**Issue by Snicon** [sgtcaze/ZombieEscape#29]
Hell, i dound this unique minigame plugin yesterday and i love the idea! Right away i wanted to try it but it didnt work. Soon i realised it was beacuse of the "ArenasPath" config thing who was returning null. Not long after that i found this https://gyazo.com/39515815acd1e2b0228dc6140ac4ebfa and i was unable to go to the site because its down. Anyone who has the guide?

// Sixten Peterson

**Comment by eliblaney** [comment]
Please note that this plugin was developed by SgtCaze for a YouTube series that, at the time of production, was created for Bukkit v1.8.8. Considering the current version is v1.13, it should be expected that major changes were done and that this plugin would no longer be flawless! Unfortunately, development for this plugin has ceased about 2 years ago, so it doesn't look like an update for 1.13 will be coming anytime soon.

However, you could always contribute to the project by updating the plugin to v1.13 yourself and pushing the updated code!

**Comment by Snicon** [comment]
Umm, im using 1.8.8... If im able to make a working version for 1.8.8 im gladly updating the plugin! ;)

EDIT: Problem Solved
